### ISSUE TITLE
Wiki on how to use Tracker

### ISSUE THREAD

**Issue by pcklink** [VisionandCognition/Tracker#3]
We could use the WIKI function on this repo to write a Tracker manual. There's an old version of a manual CvdT wrote a long time ago, but some of the things in it are outdated and it's a bit minimal. Perhaps we can converge on a preferred way to use Tracker and add that information as well.

I'm thinking of things like:

- [ ] Requirements list (OS, 32/64 bit, Matlab version)
- [ ] Using a launch script
- [ ] Separating run-code, stimulus-settings, and behavioral control settings in different files
- [ ] Saving log files
- [ ] JSON files
- [ ] Hardware integration (connection box, triggers, photodiode)
